// Welcome to Terry-2
//
// Terry is a cellular automata simulator written in Rust. It is designed to be super fast so we can
// simulate large worlds with many different types of cells.
// Anything that can be determined at build time is determined at build time, so we can optimize the
// code for the specific world we want to simulate. This means that we can have a very large number
// of different cell types without sacrificing performance.
//
// The ultimate goal is to create an automata that can solve https://docs.arcprize.org/
//
// However, step 1 is simply to choose the right action for the first move of the first level of the
// simplest game, "ls20".
// Since ARC3 is implemented in python, we  load the initial frame from a JSON file in
// `arc3_agi/initial_frame.json`. This file is generated by the `arc3_agi/script.py` script, which
// uses the `arc3_agi` crate to create an environment and extract the initial frame.
//
// The JSON format is a list[list[list[uint8]]] where the first dimension is the number of frames
// (in this case, 1), the second dimension is the height of the frame, and the third dimension is the
// width of the frame. Each uint8 value represents a cell type.
// So frame_data[0] is the first frame, frame_data[0][y] is the y-th row of the first frame (counting
// from the top), and frame_data[0][y][x] is the x-th cell in the y-th row of the first frame (
// counting from the left).
//
// The frame is 64x64

use std::fs;
use std::path::Path;
use image::{ImageBuffer, Rgba};

fn load_initial_frame(frame_path: &Path) -> Vec<Vec<u8>> {
    let frame_json = fs::read_to_string(frame_path).unwrap_or_else(|error| {
        panic!("Failed to read {}: {error}", frame_path.display());
    });

    let frame_data: Vec<Vec<Vec<u8>>> = serde_json::from_str(&frame_json).unwrap_or_else(|error| {
        panic!("Failed to parse {} as JSON: {error}", frame_path.display());
    });

    let initial_frame: Vec<Vec<u8>> = frame_data
        .into_iter()
        .next()
        .unwrap_or_else(|| panic!("{} did not contain any frames", frame_path.display()));

    if initial_frame.len() != 64 || initial_frame.iter().any(|row| row.len() != 64) {
        panic!(
            "Expected a 64x64 frame in {}, got {}x{}",
            frame_path.display(),
            initial_frame.len(),
            initial_frame.first().map_or(0, |row| row.len())
        );
    }

    initial_frame
}

fn render_frame(frame: &[Vec<u8>]) {
    // Create a PNG file and write the frame to it using these color mappings for the cell types:
    //    Value │   Hex Color   │ Color Name
    // ─────────┼───────────────┼──────────────
    //     0    │  #FFFFFFFF  │ White
    //     1    │  #CCCCCCFF  │ Off-white
    //     2    │  #999999FF  │ Neutral Light
    //     3    │  #666666FF  │ Neutral
    //     4    │  #333333FF  │ Off Black
    //     5    │  #000000FF  │ Black
    //     6    │  #E53AA3FF  │ Magenta
    //     7    │  #FF7BCCFF  │ Magenta Light
    //     8    │  #F93C31FF  │ Red
    //     9    │  #1E93FFFF  │ Blue
    //     10   │  #88D8F1FF  │ Blue Light
    //     11   │  #FFDC00FF  │ Yellow
    //     12   │  #FF851BFF  │ Orange
    //     13   │  #921231FF  │ Maroon
    //     14   │  #4FCC30FF  │ Green
    //     15   │  #A356D6FF  │ Purple
    const PALETTE: [[u8; 4]; 16] = [
        [0xFF, 0xFF, 0xFF, 0xFF],
        [0xCC, 0xCC, 0xCC, 0xFF],
        [0x99, 0x99, 0x99, 0xFF],
        [0x66, 0x66, 0x66, 0xFF],
        [0x33, 0x33, 0x33, 0xFF],
        [0x00, 0x00, 0x00, 0xFF],
        [0xE5, 0x3A, 0xA3, 0xFF],
        [0xFF, 0x7B, 0xCC, 0xFF],
        [0xF9, 0x3C, 0x31, 0xFF],
        [0x1E, 0x93, 0xFF, 0xFF],
        [0x88, 0xD8, 0xF1, 0xFF],
        [0xFF, 0xDC, 0x00, 0xFF],
        [0xFF, 0x85, 0x1B, 0xFF],
        [0x92, 0x12, 0x31, 0xFF],
        [0x4F, 0xCC, 0x30, 0xFF],
        [0xA3, 0x56, 0xD6, 0xFF],
    ];

    let height = frame.len() as u32;
    let width = frame.first().map_or(0_u32, |row| row.len() as u32);
    let mut image = ImageBuffer::<Rgba<u8>, Vec<u8>>::new(width, height);

    for (y, row) in frame.iter().enumerate() {
        for (x, value) in row.iter().enumerate() {
            let color = PALETTE
                .get(*value as usize)
                .unwrap_or_else(|| panic!("Cell value {} at ({}, {}) is out of palette range 0..=15", value, x, y));
            image.put_pixel(x as u32, y as u32, Rgba(*color));
        }
    }

    let output_path = Path::new("arc3_agi/initial_frame.png");
    image.save(output_path).unwrap_or_else(|error| {
        panic!("Failed to save {}: {error}", output_path.display());
    });
}
fn main() {
    // Load the initial frame from the JSON file into a 2D u8 array
    let frame_path = Path::new("arc3_agi/initial_frame.json");
    let initial_frame = load_initial_frame(frame_path);

    println!(
        "Loaded initial frame: {}x{}",
        initial_frame.len(),
        initial_frame[0].len()
    );

    render_frame(&initial_frame);
    println!("Rendered frame to arc3_agi/initial_frame.png");
}
